package com.parkshark.dudewheremycar.security;

public enum Feature {
    CREATE_PARKING_LOT_PARKSHARK,
    GET_ALL_PARKING_LOTS_PARKSHARK,

    CREATE_PARKING_SPOT_ALLOCATION_PARKSHARK,
    STOP_PARKING_SPOT_ALLOCATION_PARKSHARK,
    GET_ALL_PARKING_SPOT_ALLOCATIONS_PARKSHARK,

    GET_ALL_MEMBERS_PARKSHARK,
    CREATE_MEMBER_PARKSHARK,

    GET_ALL_DIVISIONS_PARKSHARK,
    GET_DIVISION_BY_ID_PARKSHARK,
    CREATE_DIVISION_PARKSHARK,
    CREATE_SUBDIVISION_PARKSHARK,

    GET_CUSTOMER_PARKSHARK,
    GET_ADMIN_PARKSHARK;
}
